id: P72D3507C
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13329
  instance_id: http://purl.bdrc.io/resource/IE3JT13329
  collection_id: http://purl.bdrc.io/resource/PR0ET001
  language_id: None
  title:
    bo:
    - ཛམྦྷ་ལ་སེར་པོའི་སྒྲུབ་ཐབས་དང་། གུ་རུ་གསོལ་འདེབས།
  alt_title:
    bo:
    - གནམ་ཆོས་ཐུགས་ཀྱི་གཏེར་ཁ་སྙན་བརྒྱུད་ཟབ་མའི་སྐོར་ལས་ཛམྦྷ་ལ་སེར་པོའི་སྒྲུབ་ཐབས་དང་།
      གུ་རུ་པདྨའི་ཚིག་བདུན་གསོལ་འདེབས་བྱིན་བརླབ་སྤྲིན་ཕུང་དངོས་གྲུབ་ཆར་རྒྱུན་མྱུར་སྩོལ།
  author: http://purl.bdrc.io/resource/P2486
  publisher: DharmaDownload
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ef83c67dd11848d2a7a7a1f9c48a1d4f:
      title: ༄༅།་།གནམ་ཆོས་ཐུགས་ཀྱི་གཏེར་ཁ་སྙན་བརྒྱུད་ཟབ་མའི་སྐོར་ལས་ཛམྦྷ་ལ་སེར་པོའི་སྒྲུབ་ཐབས་བཞུགས་སོ།་།
      volume_number: 1
      base_file: UT3JT13329_001_0000.txt
      reference: http://purl.bdrc.io/resource/VLDE8AC9A51231145D
      image_group: null
      quality: null
    615af4094325494fb016c8d5dad3bcf3:
      title: ན་མོ་གུ་རུ༔གུ་རུ་པདྨའི་ཚིག་བདུན་གསོལ་འདེབས་བྱིན་བརླབ་སྤྲིན་ཕུང་དངོས་གྲུབ་ཆར་རྒྱུན་མྱུར་སྩོལ་ནི།གཏེར་ཞལ་ཕྱེ་དང་ཤོག་སེར་ཕབ༔གཞན་ཡང་
      volume_number: 2
      base_file: UT3JT13329_002_0000.txt
      reference: http://purl.bdrc.io/resource/VLF91205CB97A6377A
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-22T11:22:04.970796'
last_modified_at: '2021-12-22T11:22:04.970803'
